coinGiftHome:
    pattern:  /home
    defaults: { _controller: CympelCoinGiftBundle:Default:index }
coinGiftCreate:
    pattern: /create
    defaults: { _controller: CympelCoinGiftBundle:Default:create }
coinGiftCampaign:
    pattern: /campaign/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:campaign }
coinGiftCreateForm:
    pattern: /create/form
    defaults: { _controller: CympelCoinGiftBundle:Default:createForm }
coinGiftTrending:
    pattern: /trending
    defaults: { _controller: CympelCoinGiftBundle:Default:trending }
coinGiftPopular:
    pattern: /popular
    defaults: { _controller: CympelCoinGiftBundle:Default:popular }
coinGiftGift:
    pattern: /gift/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:gift }
coinGiftGiftForm:
    pattern: /gift/form/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:giftForm }
coinGiftComments:
    pattern: /comments/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:comments }
coinGiftSubComments:
    pattern: /sub/comments/{$commentId}
    defaults: { _controller: CympelCoinGiftBundle:Default:subComments }
coinGiftVoteUsername:
    pattern: /vote/{commentId}/{username}/{voteValue}
    defaults: { _controller: CympelCoinGiftBundle:Default:voteUsername }
coinGiftVote:
    pattern: /vote/{commentId}/{voteValue}
    defaults: { _controller: CympelCoinGiftBundle:Default:vote }
coinGiftNewCampaignComment:
    pattern: /new/campaign/comment/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:newCampaignComment }
coinGiftNewCommentComment:
    pattern: /new/comment/comment/{parentCommentId}
    defaults: { _controller: CympelCoinGiftBundle:Default:newCommentComment }
coinGiftGifters:
    pattern: /gifters/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:gifters }