coinGiftHome:
    pattern:  /home
    defaults: { _controller: CympelCoinGiftBundle:Default:index }
coinGiftCreate:
    pattern: /create
    defaults: { _controller: CympelCoinGiftBundle:Default:create }
coinGiftCampaign:
    pattern: /campaign/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:campaign }
coinGiftCreateForm:
    pattern: /create/form
    defaults: { _controller: CympelCoinGiftBundle:Default:createForm }
coinGiftTrending:
    pattern: /trending
    defaults: { _controller: CympelCoinGiftBundle:Default:trending }
coinGiftPopular:
    pattern: /popular
    defaults: { _controller: CympelCoinGiftBundle:Default:popular }
coinGiftGift:
    pattern: /gift/{campaignName}
    defaults: { _controller: CympelCoinGiftBundle:Default:gift }