parameters:
#    cympel_coin_gift.example.class: Cympel\Bundle\CoinGiftBundle\Example

services:
#    cympel_coin_gift.example:
#        class: %cympel_coin_gift.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
